#!/usr/bin/env python3
"""
PR Generator Engine
Generates Pull Requests for cost optimization changes
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass

from finops.savings_ledger import Opportunity, OpportunityType

@dataclass
class PRChange:
    """Represents a change in a PR"""
    file_path: str
    change_type: str  # 'terraform', 'kubernetes', 'karpenter', 'keda'
    before: Dict
    after: Dict
    description: str

@dataclass
class PullRequest:
    """Pull request for cost optimization"""
    title: str
    description: str
    opportunity_id: str
    branch_name: str
    changes: List[PRChange]
    estimated_savings: float
    risk_score: float
    evidence: Dict

class PRGenerator:
    """Generates PRs for cost optimization opportunities"""
    
    def __init__(self, repo_path: str, github_token: Optional[str] = None):
        self.repo_path = repo_path
        self.github_token = github_token or os.getenv('GITHUB_TOKEN')
    
    def generate_pr(self, opportunity: Opportunity) -> PullRequest:
        """Generate a PR for an opportunity"""
        
        if opportunity.type == OpportunityType.OVER_REQUESTED_CPU:
            return self._generate_cpu_rightsize_pr(opportunity)
        elif opportunity.type == OpportunityType.OVER_REQUESTED_MEMORY:
            return self._generate_memory_rightsize_pr(opportunity)
        elif opportunity.type == OpportunityType.IDLE_NODES:
            return self._generate_node_consolidation_pr(opportunity)
        elif opportunity.type == OpportunityType.ORPHAN_VOLUMES:
            return self._generate_volume_cleanup_pr(opportunity)
        else:
            raise ValueError(f"Unsupported opportunity type: {opportunity.type}")
    
    def _generate_cpu_rightsize_pr(self, opp: Opportunity) -> PullRequest:
        """Generate PR for CPU right-sizing"""
        changes = []
        
        # Generate K8s manifest change
        k8s_file = f"k8s/{opp.namespace}/{opp.workload}.yaml"
        changes.append(PRChange(
            file_path=k8s_file,
            change_type='kubernetes',
            before=opp.before_state,
            after=opp.after_state,
            description=f"Right-size CPU request from {opp.before_state['cpu_request']} to {opp.after_state['cpu_request']:.2f} cores"
        ))
        
        return PullRequest(
            title=f"Cost Optimization: Right-size CPU for {opp.workload}",
            description=f"""
## Cost Optimization Opportunity

**Type**: CPU Right-sizing
**Workload**: {opp.workload}
**Namespace**: {opp.namespace}
**Cluster**: {opp.cluster}

### Impact
- **Estimated Monthly Savings**: ${opp.estimated_monthly_savings:.2f}
- **Confidence**: {opp.confidence:.0%}
- **Risk Score**: {opp.risk_score:.0%}

### Changes
- CPU request: {opp.before_state['cpu_request']} → {opp.after_state['cpu_request']:.2f} cores
- CPU limit: {opp.before_state.get('cpu_limit', 'N/A')} → {opp.after_state.get('cpu_limit', 'N/A')} cores

### Evidence
- Current CPU utilization: {opp.evidence.get('utilization', 0):.1%}
- Current CPU usage: {opp.evidence.get('current_cpu_usage', 0):.2f} cores

### Recommendation
{opp.evidence.get('recommendation', 'Reduce CPU requests based on actual usage')}

---
*Generated by AI DevOps Brain FinOps Engine*
            """.strip(),
            opportunity_id=opp.id,
            branch_name=f"finops/cpu-rightsize-{opp.workload}-{datetime.utcnow().strftime('%Y%m%d')}",
            changes=changes,
            estimated_savings=opp.estimated_monthly_savings,
            risk_score=opp.risk_score,
            evidence=opp.evidence
        )
    
    def _generate_memory_rightsize_pr(self, opp: Opportunity) -> PullRequest:
        """Generate PR for memory right-sizing"""
        changes = []
        
        k8s_file = f"k8s/{opp.namespace}/{opp.workload}.yaml"
        changes.append(PRChange(
            file_path=k8s_file,
            change_type='kubernetes',
            before=opp.before_state,
            after=opp.after_state,
            description=f"Right-size memory request from {opp.before_state['memory_request_gb']:.2f}GB to {opp.after_state['memory_request_gb']:.2f}GB"
        ))
        
        return PullRequest(
            title=f"Cost Optimization: Right-size Memory for {opp.workload}",
            description=f"""
## Cost Optimization Opportunity

**Type**: Memory Right-sizing
**Workload**: {opp.workload}
**Namespace**: {opp.namespace}
**Cluster**: {opp.cluster}

### Impact
- **Estimated Monthly Savings**: ${opp.estimated_monthly_savings:.2f}
- **Confidence**: {opp.confidence:.0%}
- **Risk Score**: {opp.risk_score:.0%}

### Changes
- Memory request: {opp.before_state['memory_request_gb']:.2f}GB → {opp.after_state['memory_request_gb']:.2f}GB
- Memory limit: {opp.before_state.get('memory_limit_gb', 'N/A')}GB → {opp.after_state.get('memory_limit_gb', 'N/A')}GB

### Evidence
- Current memory utilization: {opp.evidence.get('utilization', 0):.1%}
- Current memory usage: {opp.evidence.get('current_memory_usage_gb', 0):.2f}GB

---
*Generated by AI DevOps Brain FinOps Engine*
            """.strip(),
            opportunity_id=opp.id,
            branch_name=f"finops/memory-rightsize-{opp.workload}-{datetime.utcnow().strftime('%Y%m%d')}",
            changes=changes,
            estimated_savings=opp.estimated_monthly_savings,
            risk_score=opp.risk_score,
            evidence=opp.evidence
        )
    
    def _generate_node_consolidation_pr(self, opp: Opportunity) -> PullRequest:
        """Generate PR for node consolidation"""
        changes = []
        
        # Generate Terraform change for node group
        tf_file = f"infrastructure/node-groups/{opp.workload}.tf"
        changes.append(PRChange(
            file_path=tf_file,
            change_type='terraform',
            before={'node_count': opp.before_state['node_count']},
            after={'node_count': opp.after_state['node_count']},
            description=f"Reduce node count from {opp.before_state['node_count']} to {opp.after_state['node_count']}"
        ))
        
        return PullRequest(
            title=f"Cost Optimization: Consolidate Nodes for {opp.workload}",
            description=f"""
## Cost Optimization Opportunity

**Type**: Node Consolidation
**Node Group**: {opp.workload}
**Cluster**: {opp.cluster}

### Impact
- **Estimated Monthly Savings**: ${opp.estimated_monthly_savings:.2f}
- **Confidence**: {opp.confidence:.0%}
- **Risk Score**: {opp.risk_score:.0%}

### Changes
- Node count: {opp.before_state['node_count']} → {opp.after_state['node_count']}
- Instance type: {opp.before_state.get('instance_type', 'N/A')} (unchanged)

### Evidence
- Average CPU utilization: {opp.evidence.get('avg_cpu_utilization', 0):.1%}
- Average memory utilization: {opp.evidence.get('avg_memory_utilization', 0):.1%}

---
*Generated by AI DevOps Brain FinOps Engine*
            """.strip(),
            opportunity_id=opp.id,
            branch_name=f"finops/node-consolidation-{opp.workload}-{datetime.utcnow().strftime('%Y%m%d')}",
            changes=changes,
            estimated_savings=opp.estimated_monthly_savings,
            risk_score=opp.risk_score,
            evidence=opp.evidence
        )
    
    def _generate_volume_cleanup_pr(self, opp: Opportunity) -> PullRequest:
        """Generate PR for volume cleanup"""
        changes = []
        
        # Generate Terraform change to remove volume
        tf_file = f"infrastructure/storage/{opp.workload}.tf"
        changes.append(PRChange(
            file_path=tf_file,
            change_type='terraform',
            before={'volume_id': opp.before_state['volume_id'], 'status': 'exists'},
            after={'volume_id': opp.after_state['volume_id'], 'status': 'deleted'},
            description=f"Delete orphaned volume {opp.before_state['volume_id']}"
        ))
        
        return PullRequest(
            title=f"Cost Optimization: Cleanup Orphaned Volume {opp.workload}",
            description=f"""
## Cost Optimization Opportunity

**Type**: Orphaned Volume Cleanup
**Volume ID**: {opp.workload}
**Cluster**: {opp.cluster}

### Impact
- **Estimated Monthly Savings**: ${opp.estimated_monthly_savings:.2f}
- **Confidence**: {opp.confidence:.0%}
- **Risk Score**: {opp.risk_score:.0%}

### Changes
- Delete orphaned EBS volume: {opp.before_state['volume_id']}
- Volume size: {opp.evidence.get('size_gb', 0)}GB
- Age: {opp.evidence.get('age_days', 0)} days

### Evidence
- Volume status: {opp.evidence.get('status', 'unknown')}
- Volume type: {opp.evidence.get('type', 'unknown')}

---
*Generated by AI DevOps Brain FinOps Engine*
            """.strip(),
            opportunity_id=opp.id,
            branch_name=f"finops/volume-cleanup-{opp.workload}-{datetime.utcnow().strftime('%Y%m%d')}",
            changes=changes,
            estimated_savings=opp.estimated_monthly_savings,
            risk_score=opp.risk_score,
            evidence=opp.evidence
        )
    
    def create_pr_files(self, pr: PullRequest) -> List[str]:
        """Create PR files in the repository"""
        created_files = []
        
        for change in pr.changes:
            file_path = os.path.join(self.repo_path, change.file_path)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            # Generate file content based on change type
            if change.change_type == 'kubernetes':
                content = self._generate_k8s_manifest(change)
            elif change.change_type == 'terraform':
                content = self._generate_terraform(change)
            else:
                content = json.dumps(change.after, indent=2)
            
            with open(file_path, 'w') as f:
                f.write(content)
            
            created_files.append(file_path)
        
        return created_files
    
    def _generate_k8s_manifest(self, change: PRChange) -> str:
        """Generate Kubernetes manifest from change"""
        # Simplified - would generate full YAML
        return f"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {change.file_path.split('/')[-1].replace('.yaml', '')}
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            cpu: "{change.after.get('cpu_request', '100m')}"
            memory: "{change.after.get('memory_request_gb', 0.5)}Gi"
          limits:
            cpu: "{change.after.get('cpu_limit', change.after.get('cpu_request', '100m'))}"
            memory: "{change.after.get('memory_limit_gb', 1.0)}Gi"
        """.strip()
    
    def _generate_terraform(self, change: PRChange) -> str:
        """Generate Terraform config from change"""
        # Simplified - would generate full Terraform
        return f"""
# {change.description}
resource "aws_eks_node_group" "example" {{
  node_count = {change.after.get('node_count', 1)}
  # ... other config
}}
        """.strip()

