#!/usr/bin/env python3
"""
Slack Integration for FinOps Approvals
Enables Slack-based approval workflow for cost optimization PRs
"""

import os
import json
import requests
from typing import Dict, Optional
from datetime import datetime
import logging

from finops.savings_ledger import Opportunity
from finops.pr_generator import PullRequest

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class SlackApprovalBot:
    """Slack bot for FinOps approvals"""
    
    def __init__(self, webhook_url: Optional[str] = None, bot_token: Optional[str] = None):
        self.webhook_url = webhook_url or os.getenv('SLACK_WEBHOOK_URL')
        self.bot_token = bot_token or os.getenv('SLACK_BOT_TOKEN')
        self.approval_channel = os.getenv('SLACK_APPROVAL_CHANNEL', '#finops-approvals')
    
    def send_approval_request(self, opportunity: Opportunity, pr: PullRequest) -> bool:
        """
        Send approval request to Slack
        
        Args:
            opportunity: Cost optimization opportunity
            pr: Generated pull request
        
        Returns:
            bool: True if sent successfully
        """
        if not self.webhook_url and not self.bot_token:
            logger.warning("Slack not configured - skipping approval request")
            return False
        
        try:
            message = self._format_approval_message(opportunity, pr)
            
            if self.bot_token:
                # Use Slack API (better for interactive buttons)
                return self._send_via_api(message, opportunity, pr)
            else:
                # Use webhook (simpler, no buttons)
                return self._send_via_webhook(message)
                
        except Exception as e:
            logger.error(f"Error sending Slack approval request: {e}")
            return False
    
    def _format_approval_message(self, opportunity: Opportunity, pr: PullRequest) -> str:
        """Format approval message"""
        savings = opportunity.estimated_monthly_savings
        confidence = opportunity.confidence
        risk = opportunity.risk_score
        
        # Risk level
        if risk < 0.3:
            risk_level = "🟢 Low"
        elif risk < 0.6:
            risk_level = "🟡 Medium"
        else:
            risk_level = "🔴 High"
        
        # Confidence level
        if confidence > 0.8:
            conf_level = "🟢 High"
        elif confidence > 0.6:
            conf_level = "🟡 Medium"
        else:
            conf_level = "🔴 Low"
        
        message = f"""
💰 *Cost Optimization Opportunity Detected*

*Opportunity*: {opportunity.type.value.replace('_', ' ').title()}
*Workload*: `{opportunity.workload}` in `{opportunity.namespace}`
*Estimated Savings*: `${savings:,.2f}/month`
*Confidence*: {conf_level} ({confidence:.0%})
*Risk Score*: {risk_level} ({risk:.0%})

*PR Ready*: {pr.branch_name}
*Changes*: {len(pr.changes)} file(s)

*Evidence*: {pr.description[:200]}...

---
*Generated by AI DevOps Brain FinOps Engine*
        """.strip()
        
        return message
    
    def _send_via_api(self, message: str, opportunity: Opportunity, pr: PullRequest) -> bool:
        """Send via Slack API with interactive buttons"""
        url = "https://slack.com/api/chat.postMessage"
        
        headers = {
            "Authorization": f"Bearer {self.bot_token}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "channel": self.approval_channel,
            "text": "Cost Optimization Opportunity",
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": message
                    }
                },
                {
                    "type": "actions",
                    "elements": [
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "✅ Approve"
                            },
                            "style": "primary",
                            "value": f"approve_{opportunity.id}",
                            "action_id": "approve_pr"
                        },
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "❌ Reject"
                            },
                            "style": "danger",
                            "value": f"reject_{opportunity.id}",
                            "action_id": "reject_pr"
                        },
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "📊 View Details"
                            },
                            "value": f"details_{opportunity.id}",
                            "action_id": "view_details"
                        },
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "❓ Explain"
                            },
                            "value": f"explain_{opportunity.id}",
                            "action_id": "explain_opportunity"
                        }
                    ]
                }
            ]
        }
        
        response = requests.post(url, headers=headers, json=payload)
        return response.status_code == 200
    
    def _send_via_webhook(self, message: str) -> bool:
        """Send via Slack webhook (simpler, no buttons)"""
        payload = {
            "text": "Cost Optimization Opportunity",
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": message
                    }
                }
            ]
        }
        
        response = requests.post(self.webhook_url, json=payload)
        return response.status_code == 200
    
    def handle_approval(self, response: Dict) -> Dict:
        """
        Handle approval/rejection from Slack
        
        Args:
            response: Slack interaction response
        
        Returns:
            Dict with action taken
        """
        action = response.get('actions', [{}])[0]
        action_id = action.get('action_id')
        value = action.get('value', '')
        
        if not value:
            return {'success': False, 'message': 'Invalid action'}
        
        parts = value.split('_', 1)
        if len(parts) != 2:
            return {'success': False, 'message': 'Invalid value format'}
        
        action_type, opportunity_id = parts
        
        if action_id == 'approve_pr':
            return self._handle_approve(opportunity_id, response)
        elif action_id == 'reject_pr':
            return self._handle_reject(opportunity_id, response)
        elif action_id == 'view_details':
            return self._handle_view_details(opportunity_id, response)
        elif action_id == 'explain_opportunity':
            return self._handle_explain(opportunity_id, response)
        else:
            return {'success': False, 'message': 'Unknown action'}
    
    def _handle_approve(self, opportunity_id: str, response: Dict) -> Dict:
        """Handle approval"""
        user = response.get('user', {}).get('name', 'unknown')
        logger.info(f"Opportunity {opportunity_id} approved by {user}")
        
        # Update opportunity status
        # Merge PR
        # Notify team
        
        return {
            'success': True,
            'message': f'Approved by {user}',
            'action': 'approve',
            'opportunity_id': opportunity_id
        }
    
    def _handle_reject(self, opportunity_id: str, response: Dict) -> Dict:
        """Handle rejection"""
        user = response.get('user', {}).get('name', 'unknown')
        logger.info(f"Opportunity {opportunity_id} rejected by {user}")
        
        # Update opportunity status
        # Close PR
        # Notify team
        
        return {
            'success': True,
            'message': f'Rejected by {user}',
            'action': 'reject',
            'opportunity_id': opportunity_id
        }
    
    def _handle_view_details(self, opportunity_id: str, response: Dict) -> Dict:
        """Handle view details request"""
        # Return detailed information about opportunity
        return {
            'success': True,
            'action': 'view_details',
            'opportunity_id': opportunity_id
        }
    
    def _handle_explain(self, opportunity_id: str, response: Dict) -> Dict:
        """Handle explain request"""
        # Generate human-readable explanation
        return {
            'success': True,
            'action': 'explain',
            'opportunity_id': opportunity_id
        }
    
    def send_notification(self, message: str, channel: Optional[str] = None) -> bool:
        """Send general notification to Slack"""
        channel = channel or self.approval_channel
        
        if self.webhook_url:
            payload = {"text": message, "channel": channel}
            response = requests.post(self.webhook_url, json=payload)
            return response.status_code == 200
        elif self.bot_token:
            url = "https://slack.com/api/chat.postMessage"
            headers = {"Authorization": f"Bearer {self.bot_token}"}
            payload = {"channel": channel, "text": message}
            response = requests.post(url, headers=headers, json=payload)
            return response.status_code == 200
        
        return False


def load_slack_bot(webhook_url: Optional[str] = None, bot_token: Optional[str] = None) -> SlackApprovalBot:
    """Convenience function to load Slack bot"""
    return SlackApprovalBot(webhook_url=webhook_url, bot_token=bot_token)


if __name__ == '__main__':
    # Test Slack integration
    bot = load_slack_bot()
    
    # Test message
    test_opportunity = Opportunity(
        id="test-123",
        type=OpportunityType.OVER_REQUESTED_CPU,
        status=OpportunityStatus.DETECTED,
        detected_at=datetime.utcnow(),
        cluster="test-cluster",
        namespace="finance",
        workload="payment-service",
        team="payments",
        estimated_monthly_savings=843.50,
        confidence=0.85,
        risk_score=0.2,
        evidence={},
        before_state={'cpu_request': 2.0},
        after_state={'cpu_request': 1.0}
    )
    
    test_pr = PullRequest(
        title="Right-size CPU for payment-service",
        description="Reduce CPU request from 2.0 to 1.0 cores",
        opportunity_id="test-123",
        branch_name="finops/cpu-rightsize-payment-service",
        changes=[],
        estimated_savings=843.50,
        risk_score=0.2,
        evidence={}
    )
    
    result = bot.send_approval_request(test_opportunity, test_pr)
    print(f"Sent: {result}")

