apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-api
  namespace: healthcare
  labels:
    app: emr-api
    cluster: healthcare
    workload: emr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emr-api
  template:
    metadata:
      labels:
        app: emr-api
        cluster: healthcare
        workload: emr
    spec:
      containers:
      - name: emr-api
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: healthcare-db-secret
              key: url
        - name: HL7_ENDPOINT
          value: "http://hl7-processor:8080"
        - name: FHIR_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emr-api
  namespace: healthcare
  labels:
    app: emr-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: emr-api

