stages:
  - validate
  - build
  - test
  - deploy
  - chaos-test

variables:
  TERRAFORM_VERSION: "1.5.0"
  KUBECTL_VERSION: "1.28.0"
  HELM_VERSION: "3.12.0"
  AWS_DEFAULT_REGION: "us-east-1"

# Terraform validation
terraform:validate:
  stage: validate
  image: hashicorp/terraform:${TERRAFORM_VERSION}
  before_script:
    - terraform --version
    - cd infrastructure
    - terraform init -backend=false
  script:
    - terraform validate
    - terraform fmt -check
  only:
    - merge_requests
    - main

# Kubernetes manifest validation
k8s:validate:
  stage: validate
  image: bitnami/kubectl:${KUBECTL_VERSION}
  script:
    - find k8s -name "*.yaml" -o -name "*.yml" | xargs -I {} kubectl --dry-run=client -f {} apply
  only:
    - merge_requests
    - main

# Python code validation
python:lint:
  stage: validate
  image: python:3.11
  before_script:
    - pip install flake8 black mypy
  script:
    - black --check ai-models/
    - flake8 ai-models/ --max-line-length=120
    - mypy ai-models/ --ignore-missing-imports
  only:
    - merge_requests
    - main

# Build AI models
build:models:
  stage: build
  image: python:3.11
  before_script:
    - pip install -r ai-models/requirements.txt
  script:
    - cd ai-models
    - python -m pytest tests/ -v
    - python anomaly-detection/train_anomaly_detector.py data/sample.csv models/
  artifacts:
    paths:
      - ai-models/models/
    expire_in: 1 week
  only:
    - main
    - tags

# Test anomaly detection
test:anomaly-detection:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r ai-models/requirements.txt
  script:
    - cd ai-models
    - python -m pytest tests/test_anomaly_detection.py -v --cov=anomaly-detection
  coverage: '/TOTAL.*\s+(\d+%)$/'
  only:
    - merge_requests
    - main

# Test RCA engine
test:rca-engine:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r ai-models/requirements.txt
  script:
    - cd ai-models
    - python -m pytest tests/test_rca_engine.py -v --cov=rca-engine
  only:
    - merge_requests
    - main

# Test auto-fix engine
test:auto-fix:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r ai-models/requirements.txt
    - kubectl version --client
  script:
    - cd ai-models
    - python -m pytest tests/test_auto_fix.py -v --cov=auto-fix
  only:
    - merge_requests
    - main

# Deploy to finance cluster
deploy:finance:
  stage: deploy
  image: alpine/helm:${HELM_VERSION}
  before_script:
    - apk add --no-cache curl
    - curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name finance-cluster --region us-east-1
  script:
    - ./scripts/deploy-platform.sh finance-cluster
    - kubectl apply -f k8s/platform/
    - kubectl apply -f simulations/finance/
  environment:
    name: finance-cluster
    url: https://finance-cluster.example.com
  only:
    - main
  when: manual

# Deploy to healthcare cluster
deploy:healthcare:
  stage: deploy
  image: alpine/helm:${HELM_VERSION}
  before_script:
    - apk add --no-cache curl
    - curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name healthcare-cluster --region us-west-2
  script:
    - ./scripts/deploy-platform.sh healthcare-cluster
    - kubectl apply -f k8s/platform/
    - kubectl apply -f simulations/healthcare/
  environment:
    name: healthcare-cluster
    url: https://healthcare-cluster.example.com
  only:
    - main
  when: manual

# Deploy to automotive cluster
deploy:automotive:
  stage: deploy
  image: alpine/helm:${HELM_VERSION}
  before_script:
    - apk add --no-cache curl
    - curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name automotive-cluster --region eu-west-1
  script:
    - ./scripts/deploy-platform.sh automotive-cluster
    - kubectl apply -f k8s/platform/
    - kubectl apply -f simulations/automotive/
  environment:
    name: automotive-cluster
    url: https://automotive-cluster.example.com
  only:
    - main
  when: manual

# Chaos testing
chaos:test:
  stage: chaos-test
  image: bitnami/kubectl:${KUBECTL_VERSION}
  before_script:
    - aws eks update-kubeconfig --name finance-cluster --region us-east-1
  script:
    - kubectl apply -f chaos/chaos-mesh/pod-kill-experiment.yaml
    - sleep 60
    - kubectl get pods -n default
    - kubectl get events --sort-by='.lastTimestamp' | tail -20
  only:
    - main
  when: manual

