apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-collector
  namespace: automotive
  labels:
    app: telemetry-collector
    cluster: automotive
    workload: iot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telemetry-collector
  template:
    metadata:
      labels:
        app: telemetry-collector
        cluster: automotive
        workload: iot
    spec:
      containers:
      - name: collector
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: KAFKA_BROKERS
          value: "kafka-finance:9092"
        - name: INGESTION_RATE
          value: "10000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-collector
  namespace: automotive
  labels:
    app: telemetry-collector
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: telemetry-collector

