apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-collector
  namespace: automotive
  labels:
    app: telemetry-collector
    cluster: automotive
    workload: iot
spec:
  replicas: 10
  selector:
    matchLabels:
      app: telemetry-collector
  template:
    metadata:
      labels:
        app: telemetry-collector
        cluster: automotive
        workload: iot
    spec:
      containers:
      - name: collector
        image: telemetry-collector:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: KAFKA_BROKERS
          value: "automotive-kafka:9092"
        - name: INGESTION_RATE
          value: "10000"  # messages per second
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-collector
  namespace: automotive
  labels:
    app: telemetry-collector
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: telemetry-collector
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: telemetry-collector-scaler
  namespace: automotive
spec:
  scaleTargetRef:
    name: telemetry-collector
  minReplicaCount: 10
  maxReplicaCount: 50
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: automotive-kafka:9092
      consumerGroup: telemetry-consumers
      topic: vehicle-telemetry
      lagThreshold: '1000'
      offsetResetPolicy: earliest

