apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: finance
  labels:
    app: payment-service
    cluster: finance
    workload: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        cluster: finance
        workload: payment
    spec:
      containers:
      - name: payment-api
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: KAFKA_BROKERS
          value: "kafka-finance:9092"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: finance-db-secret
              key: url
        - name: REDIS_URL
          value: "redis-finance:6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: finance
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: payment-service

